
run_name: "run_test"

#==========================================================================
protein_name: "WDR91" # Protein Name
Train: 'Y' # Running trian phase (N:for no, Y: for yes)
Test: 'Y' # Running test phase (N:for no, Y: for yes)
Screen: 'Y'  # Running test phase (N:for no, Y: for yes)
#==========================================================================


# Data:

train_data: [Data/TrainFiles/small_train.parquet]
test_data: [Data/TestFiles/small_test.parquet]
            
# desired_columns:  [ECFP4, ECFP6, FCFP4, FCFP6, TOPTOR, MACCS, RDK, AVALON, ATOMPAIR]                
desired_columns: [ECFP4, ECFP6] # Correct format: [ECFP4], and [ECFP4, ECFP6, ...] if multuple columns
label_column_train: [DELLabel]
label_column_test: [Label]
nrows_train: 'None' # integer or 'None' 
nrows_test: 'None'
feature_fusion_method: 'None' # options: None, All, Pairwise

# create_balanced_datasets
balance_flag: False # Creating blanced train sets (True/False)
balance_ratios: [1, 2] # balance_ratios: [1, 2, 4, 8]
#==========================================================================


# Screening:
#==========================================================================
screen_data: [Data/ScreenFiles/ScreenData1.csv, Data/ScreenFiles/ScreenData2.csv]
smiles_column: "SMILES"
chemistry_filters: 'y' #  (N:for no, Y: for yes)
#==========================================================================



# Model
#==========================================================================
# Supported models:
# rf: Random Forest
# lr: Logistic Regression
# ridge: Ridge Classifier
# sgd: Stochastic Gradient Descent Classifier
# perceptron: Perceptron
# svc: Support Vector Classifier
# nb: Gaussian Naive Bayes
# dt: Decision Tree
# knn: K-Nearest Neighbors
# gb: Gradient Boosting
# ada: AdaBoost
# bag: Bagging Classifier
# mlp: Multi-layer Perceptron
# desired_models: [rf, lr, ridge, sgd, perceptron, svc, nb, dt, knn, gb, ada, bag, mlp
desired_models: [rf] 

# Models' Hyperparameters tuning
hyperparameters_tuning: 'N' #  (N:for no, Y: for yes)

# Specifying hyperparameters
hyperparameters: {rf:{n_estimators: 150, max_depth: 10},
                  nb:{n_estimators: 150, max_depth: 10}} # hyperparameters: {}  # use default

# Cross validation
Nfold: 2 # Number of folds for the Crossfold validatrion method
#==========================================================================


# Conformal Prediction
#==========================================================================
conformal_prediction: 'N' # Running conformal prediction (N:for no, Y: for yes)
confromal_test_size: 0.3
confromal_confidence_level: 0.95
#==========================================================================



# Model selection
#==========================================================================
trainfile_for_modelselection: [] # If empty, the top model by evaluation columns and result on the evaluation set is selected. Example: trainfile_for_modelselection: WDR91_SGC.parquet
evaluationfile_for_modelselection: [] # If empty, the top model by evaluation columns is selected. Exmple: evaluationfile_for_modelselection: evaluation.parquet
evaluation_column: [Test_F1 Score, Test_Precision, Test_Recall, Test_Accuracy, Test_PlatePPV, Test_DivPlatePPV]
crossvalidation_column: [CV_F1 Score, CV_Precision, CV_Recall, CV_Accuracy, CV_PlatePPV, CV_DivPlatePPV]
#==========================================================================



# Model Fusion
#==========================================================================
Fusion: 'y' # Running test phase (N:for no, Y: for yes)
num_top_models: 2
#==========================================================================





