Fusion: y
Nfold: 2
Screen: Y
Test: Y
Train: Y
balance_flag: false
balance_ratios:
- 1
- 2
chemistry_filters: y
conformal_prediction: N
confromal_confidence_level: 0.95
confromal_test_size: 0.3
crossvalidation_column:
- CV_F1 Score
- CV_Precision
- CV_Recall
- CV_Accuracy
- CV_PlatePPV
- CV_DivPlatePPV
desired_columns:
- ECFP4
- ECFP6
- FCFP4
- FCFP6
- TOPTOR
- MACCS
- RDK
- AVALON
- ATOMPAIR
desired_models:
- rf
- lr
- sgd
- svc
- nb
- dt
- knn
- gb
- ada
- bag
- mlp
evaluation_column:
- Test_F1 Score
- Test_Precision
- Test_Recall
- Test_Accuracy
- Test_PlatePPV
- Test_DivPlatePPV
evaluationfile_for_modelselection: []
feature_fusion_method: None
hyperparameters:
  rf:
    max_depth: 10
    n_estimators: 150
hyperparameters_tuning: N
label_column_test:
- Label
label_column_train:
- DELLabel
nrows_test: null
nrows_train: null
num_top_models: 2
protein_name: WDR91
run_name: run_test
screen_data:
- Data/ScreenFiles/ScreenData1.csv
- Data/ScreenFiles/ScreenData2.csv
smiles_column: SMILES
test_data:
- Data/TestFiles/small_test.parquet
train_data:
- Data/TrainFiles/small_train.parquet
trainfile_for_modelselection: []
